[package]
name = "sinfo-cli"
version = "0.1.0"
authors = ["zhaoyz <954241552@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.15.9"
clap = "2.33.3"
